server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      server:
        webflux:
          discovery:
            locator:
              enabled: false

          routes:
            - id: auth-service
              uri: lb://auth-service
              predicates:
                - Path=/api/auth/**

            - id: shipments-service
              uri: lb://shipments-service
              predicates:
                - Path=/api/shipments/**
              filters:
                # Le Gateway a déjà validé le JWT.
                - RemoveRequestHeader=Cookie

security:
  jwt:
    issuer: parcel-shipping-auth-service
    audience: parcel-shipping-backoffice
    secret: ${AUTH_JWT_SECRET}

    cookie:
      name: parcel_access_token

eureka:
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

management:
  info:
    env:
      enabled: true